import Head from "next/head";
import styles from "@/styles/main.module.scss";
import AppShellComponent from "@/components/appShellComponent/AppShellComponent";
import HomepageEl from "@/components/homepageEl/HomepageEl";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/difficulty.ico" />
      </Head>
      <AppShellComponent hideNavbar={true}>
        <main className={`${styles.main}`}>
          <HomepageEl />
        </main>
      </AppShellComponent>
    </>
  );
}
